# Configuration file for running sensitivity analysis with 'ESLiM' energy-source share model
#
# use this with sensitivity.py
#
# path to configuration for model
baseline_model_config: /Users/lindseygulden/dev/leg-up-private/projects/iam/config/eslim_baseline_config.yml
#
sampler: saltelli #or lhs
num_samples: 32768 #65536 # number of samples to run with LHS if sampler = lhs
calc_second_order: False
metric: fossil_fuels_with_CCS
output_dir: /Users/lindseygulden/dev/leg-up-private/projects/iam/data/revised_data_20260116_sens
pars_to_vary:
  - name: starting_price_solar_pv
    key_path:
    - parameters
    - starting_energy_generation_price_usd_per_mwh
    - solar_pv
    bounds:
    - 50
    - 110
  - name: ccs_cost_adder_fraction
    key_path:
    - parameters
    - starting_carbon_removal_price_fraction
    - fossil_fuels_with_CCS
    bounds:
    - 0.35
    - 1.0
  - name: ccs_capture_fraction
    key_path:
    - parameters
    - capture_fraction
    - fossil_fuels_with_CCS
    bounds:
    - 0.1
    - 0.9
  - name: solar_pv_learning_curve
    key_path:
    - parameters
    - frac_energy_generation_cost_decrease_per_timestep
    - solar_pv
    bounds:
    - 0.05
    - 0.4
  - name: ccs_learning_curve
    key_path:
    - parameters
    - frac_cdr_cost_decrease_per_timestep
    - fossil_fuels_with_CCS
    bounds:
    - 0.0
    - 0.15
  - name: fossil_subsector_logit_exponent
    key_path:
    - logit_exponents
    - subsector
    - fossil
    bounds:
    - -10.0
    - -1
  - name: energy_sector_logit_exponent
    key_path:
    - logit_exponents
    - sector
    - energy
    bounds:
    - -10.0
    - -1
  - name: co2_starting_price
    key_path:
    - price_curve
    - starting_price
    bounds:
    - 0
    - 50
  - name: co2_total_increase_in_price
    key_path:
    - price_curve
    - total_increase_in_price
    bounds:
    - 0
    - 200
